### ISSUE TITLE
Mobile Templates

### ISSUE THREAD

**Issue by dansup** [dansup/bulma-templates#17]
Currently, many of the templates don't render properly on mobile devices. I plan to add mobile support to every template and this issue will track it.

Broken Mobile Templates:
- blog post
- profile
- status page
- timeline
- video player

Mobile ready templates:
- admin
- blog
- cover
- gallery grid
- hero
- landing
- login
- product
- projects
- register

**Comment by RafaelAybar** [comment]
Hi, do you have any responsive template? I am try to learn to use bulma framework but I dont know how its works

**Comment by dansup** [comment]
@RafaelAybar Technically all the templates are [responsive](http://bulma.io/documentation/overview/responsiveness/), though some need a bit of work to better support the 4 breakpoints. You can test this on a desktop browser, browse a few [themes](https://dansup.github.io/bulma-templates/) and resize the browser window.
