### ISSUE TITLE
Template Requests

### ISSUE THREAD

**Issue by dansup** [dansup/bulma-templates#18]
My original goal for this project was to create a bunch of templates that showcase what you can do with bulma.

If you have any ideas or suggestions for a new template, post a comment in this issue and I will do my best to accommodate everyones requests.

**Comment by xdevnull** [comment]
In the blog section, You've the "View more posts" href.

Can you create the template for "view more posts"?

I could do it by my own. But your designs are simple and impressive!

Thumbs up!

**Comment by dansup** [comment]
@xdevnull Thanks! I have been working on finishing the [blog](https://dansup.github.io/bulma-templates/templates/blog.html) and [blog post](https://dansup.github.io/bulma-templates/templates/blog-post.html) templates, I will add this to my todo list and get it included in the latest updates.

**Comment by gpetrov** [comment]
Maybe a dark theme for Bulma? Like a dark admin.

**Comment by dansup** [comment]
@gpetrov Thanks! I will add it to my todo list.

**Comment by stevebauman** [comment]
These are awesome templates! Thanks @dansup!

**Comment by roccomuso** [comment]
@dansup Thanks! Hope to see more awesome templates soon ;)

**Comment by 13ens** [comment]
Thanks for all the templates, can you include some sidebar templates? thanks man!

**Comment by dansup** [comment]
Thanks for the requests, I have added them to my list of ideas for new templates.
