### ISSUE TITLE
GRID with 'panel-block' and wondering about TILES with 'ancestor-parent-child'

### ISSUE THREAD

**Issue by tweed** [dansup/bulma-templates#21]
Seriously AWESOME. Just found your updates and have been thinking to have... 
-- hero with grid-gallery underneath. 

So, starting with hero.html (NICE!) then I figured to cut the grid portion out of grid-gallery.html, 

In past months i've been trying stuff with the grid/tiles page at:
http://bulma.io/documentation/grid/tiles/

Then noticed - you're using   `<div class="panel-block">` for the grid stuff.
Wanted to ask you if there's a reason for using that instead of the way it is in the doc at bulma.io?

```
<div class="tile is-ancestor">
<div class="tile is-parent is-vertical">
<article class="tile is-child box">
```

As a beginner and a hack at that,, right now I can only add that the way the tiles (ancestor-parent-child) works in the docs at  http://bulma.io/documentation/grid/tiles/ might have some flexibility at some point though i don't really know yet.

interested to know if you like, or may use the tiles (ancestor-parent-child) stuff in any template. 
I'm guessing that i'll need some of what i see when resizing and reading the features at  http://bulma.io/documentation/grid/tiles/ .

Sorry I haven't thought of how to explain it much yet.

Whatever happens - KNOCKED OUT HAPPY about your work !

**Comment by dansup** [comment]
Thanks for the feedback @tweed. I originally planned to make a grid gallery and grid tile template to show the difference in using columns/panels and tiles for a grid. I hope to have the grid tile template up soon!

**Comment by tweed** [comment]
extremely interesting!! Can't thank you enough. motivating stuff.

**Comment by dansup** [comment]
@tweed I added a new [metro tile grid template](https://dansup.github.io/bulma-templates/templates/grid-metro.html). After I finish updating the other templates, I will spend a bit more time polishing it up and maybe add some js to show different tile layouts or something.

**Comment by tweed** [comment]
YES - i KNOW! *-) though only found your writing above just now --- really really sUper great!
