### ISSUE TITLE
Templates are kinda broken with latest Bulma

### ISSUE THREAD

**Issue by hugows** [dansup/bulma-templates#32]
Its unfortunate but it seems that with the latest versions some templates are broken, new classes seem to have been added in the framework. Have you tried it? :(

**Comment by dansup** [comment]
@hugows Yes, I have noticed. These templates were developed for bulma 0.1.0. I am working on updating them all to version 0.3.0 in an upcoming release.

**Comment by hugows** [comment]
Great job btw, I think its a great selling point of the Bootstrap site - and the Bulma guys should put you on their Frontpage!!
