### ISSUE TITLE
Login theme

### ISSUE THREAD

**Issue by xereda** [dansup/bulma-templates#33]
The "login" theme is different from the one shown in the demo. Please check.

**Comment by xereda** [comment]
![captura de tela 2017-03-28 as 16 01 27](https://cloud.githubusercontent.com/assets/14337850/24422419/e7a7a5a4-13cf-11e7-8660-3747d359600c.png)

![captura de tela 2017-03-28 as 16 01 48](https://cloud.githubusercontent.com/assets/14337850/24422422/e7ca5f86-13cf-11e7-8648-3c59345ab15e.png)

**Comment by dansup** [comment]
@xereda Yes, I am in the middle of deploying the updated templates. I have not yet updated the thumbnails or website. If you are looking for the old login template, check the [latest tag](https://github.com/dansup/bulma-templates/tree/0.0.2).

**Comment by roccomuso** [comment]
@dansup I love the latest style ;) keep up the good work.

**Comment by jartaud** [comment]
``
background-blend-mode: screen
``

hides the background image. Chrome 59 - 60 beta

**Comment by dansup** [comment]
That template is now deprecated with the release of the newer versions, if you encounter any issues with the newer templates please open a new issue.
