### ISSUE TITLE
Variable override examples?

### ISSUE THREAD

**Issue by tu5** [dansup/bulma-templates#34]
Hey,
I'm having really hard time with Skeleton theme. I just change few simple elements. But it doesn't take any effects.

With below variables - only primary color changes, background or grey-lighter (it has to be quote/code box) doesn't make any change, though I can see those hex codes in output .css.

```
$body-background: #FAF3DD
$primary: #55AA55
$grey-lighter: #C8D5B9
```
Could you please provide some variable override example? Thank you for your work!

**Comment by dansup** [comment]
I didn't use any custom overrides, most of the templates use bulma v 0.1.2. I am in the process of updating them to v 0.4.0+

**Comment by tu5** [comment]
@dansup thanks, good luck with that! Can't wait for "skeleton" :)
