### ISSUE TITLE
Logo without margin

### ISSUE THREAD

**Issue by xereda** [dansup/bulma-templates#36]
Logo without margin

The logo is running out of time when the site is in lower resolutions, such as mobile.

Look at this:

![logo](https://cloud.githubusercontent.com/assets/14337850/25012411/cce7f8f8-2046-11e7-87eb-23a31c101a75.gif)

**Comment by dansup** [comment]
Good find! I will fix this in a future release.

**Comment by dansup** [comment]
That template is now deprecated with the release of the newer versions, if you encounter any issues with the newer templates please open a new issue.
