### ISSUE TITLE
Thanks so much

### ISSUE THREAD

**Issue by dariusgarza** [dansup/bulma-templates#38]
These templates are extremely helpful! Thanks so much for putting this together. This should really be integrated into the original project's demos or something. They're also well designed and nice to look at. Bravo!!

**Comment by fernandoguedes** [comment]
Yes @dariusgarza is very helpful! Thanks @dansup for the great work!

**Comment by dansup** [comment]
No problem! Bulma is an exciting new css framework and I look forward to releasing the new updated templates.

**Comment by METACEO** [comment]
@dansup I was about to create another issue to give thanks!
