### ISSUE TITLE
Login template issue with height in Safari

### ISSUE THREAD

**Issue by chvanikoff** [dansup/bulma-templates#39]
In a login template there's a tiny vertical scroll and empty space at the bottom appearing when using Safari. In Chrome everything is fine.
[bug screenshoted](https://puu.sh/wAGr1/04649638d4.png)

**Comment by flosommerfeld** [comment]
Had the same problem with firefox. Probably not the best solution but this is how i fixed it:
`
<style>
    @media screen and (max-height: 650px) {
      body {
        overflow-x: hidden;
        overflow-y: scroll;
      }
    }

    @media screen and (min-height: 651px) {
      body {
        overflow-x: hidden;
        overflow-y: hidden;
      }
    }
  </style>`

**Comment by dansup** [comment]
This will be fixed in an upcoming release.

**Comment by dansup** [comment]
That template is now deprecated with the release of the newer versions, if you encounter any issues with the newer templates please open a new issue.
