### ISSUE TITLE
which bulma version is used here? it's not the latest one

### ISSUE THREAD

**Issue by mickeyren** [dansup/bulma-templates#41]
i use `  "bulma": "^0.5.1",` and the hero page looks like this:

![2017-08-31 at 9 49 am](https://user-images.githubusercontent.com/175045/29902612-b2dad134-8e31-11e7-9615-c89bf53d72e6.jpg)

broken in some parts.

**Comment by israelroldan** [comment]
It appears that this project has bundled bulma inside its css directory, so there's really no indicative of which version it was other than it is older than a year.

The issue in your screenshot is most likely caused by the deprecation of the 'nav' component in favour of 'navigation': http://bulma.io/documentation/components/navbar/

Hope that helps

**Comment by dansup** [comment]
@mickeyren The bulma version is 0.1.1, released over a year ago. https://github.com/jgthms/bulma/releases/tag/0.1.1

**Comment by m0a** [comment]
your template is awesome!. but bulma version is old. 
Are you planning to update bulma?

**Comment by dansup** [comment]
@m0a Thanks, yes I am working on updated versions. There have been a lot of changes since 0.1.1, I have created a few new templates and updated older ones, however they are now outdated so it will take some time to catch up.

**Comment by israelroldan** [comment]
@dansup do you have a branch I can contribute to? I have a couple ideas for this repo (namely enabling [bulmaswatch](https://jenil.github.io/bulmaswatch/) in your templates and actually use the latest bulma release).

**Comment by dansup** [comment]
I have updated 5 templates to the latest bulma version (0.5.3) and plan to update the rest soon. You can submit PR's to the development branch (master).

@israelroldan I like the bulmaswatch idea, could use javascript on the demo site to switch between different swatches.
