### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by AndySoHotRightNow** [dansup/bulma-templates#45]
Hi,

Hope that you won't mind if I point out there's a typo on the page, it should read "receive" and not "recieve".

Looking forward to a flourishing template collection,

Andy
![screen shot 2017-10-12 at 1 21 07 pm](https://user-images.githubusercontent.com/17130123/31480424-5e87e078-af50-11e7-98dc-935f8377c101.png)

**Comment by israelroldan** [comment]
@AndySoHotRightNow in case you'd like to fix this typo yourself, it is really simple, you can even do it in the browser.

1. Just browse to [the file with the typo](https://github.com/dansup/bulma-templates/blob/master/index.html) and click in the little pencil button. This will create a fork of the project under your user. 
2. Correct the typo and commit the change in your browser.
3. Browse back to this repository, GitHub will show you a big "Compare" button that allows you to create a pull request to actually merge your change.
4. Submit your PR and @dansup will take it from there.

I hope you don't mind me outlining these steps, I'm just trying to help in case this is your first contribution. Success!

**Comment by AndySoHotRightNow** [comment]
Indeed it is!

Thank you so much for the detailed instructions, will know what to do next time.

And... pull request created!

**Comment by dansup** [comment]
@AndySoHotRightNow Thanks, this is fixed in #46
