### ISSUE TITLE
a few suggestions

### ISSUE THREAD

**Issue by diomed** [dansup/bulma-templates#50]
hello

I'd like to suggest that you change navigation for :
https://dansup.github.io/bulma-templates/templates/blog.html
to same one that is in hero and cover.

I see that navigation is currently broken - not styled properly that is.

(may I contact you on gitter for some template ideas?)

**Comment by dansup** [comment]
@diomed Thanks for the report, I am still working on the admin/blog templates so I will fix that in an upcoming release. 

I pinged you on gitter.im/jgthms/bulma - feel free to contact me on gitter or in #bulma-templates on freenode.
