### ISSUE TITLE
Request a vertical mega menu template!

### ISSUE THREAD

**Issue by loongmxbt** [dansup/bulma-templates#51]
I've found a left mega menu (vertical mega menu) is popular among sites. I've also found that bulma supports dropdown mega menu natively. Could someone made a menu like this in bulma? Thanks a lot!

https://github.com/kamens/jQuery-menu-aim
https://www.amazon.com/
http://www.aliexpress.com/

**Comment by dansup** [comment]
I will consider this for a future template. Thanks!
