### ISSUE TITLE
aside

### ISSUE THREAD

**Issue by elKaZe** [dansup/bulma-templates#52]
would you do an aside template with the new version of bulma? I'm using it in one of my projects, it looks great

by the way, great code of conduct :D

**Comment by Talkingbaby** [comment]
@elKaZe hey I could be misunderstanding but what kind of aside template do you mean?

**Comment by elKaZe** [comment]
Sorry, I didn't add the enough context of what I was talking.

If you look [here](https://github.com/dansup/bulma-templates/tree/a48483d571caabe3c375ee2a662961883c7c95de) you could find the repo when the aside template still was.
* [aside.html](https://github.com/dansup/bulma-templates/blob/a48483d571caabe3c375ee2a662961883c7c95de/templates/aside.html)
* [aside.css](https://github.com/dansup/bulma-templates/blob/a48483d571caabe3c375ee2a662961883c7c95de/css/aside.css)

**Comment by Talkingbaby** [comment]
I'll take a look at it.

**Comment by dansup** [comment]
@elKaZe Hello. I am in the process of updating all the templates to the latest bulma version. I don't have an ETA but I am open to pull requests! 

cc @Talkingbaby

**Comment by Talkingbaby** [comment]
@dansup @elKaZe 

I just created a new aside nav drawer. It can be used in place of or as another template. The PR is here: https://github.com/dansup/bulma-templates/pull/53

**Comment by dansup** [comment]
#53 is an open PR that adds an aside template. Thanks again @Talkingbaby
