### ISSUE TITLE
Pingy Web Scaffold

### ISSUE THREAD

**Issue by davej** [dansup/bulma-templates#54]
Hey @dansup, I created a [Web Scaffold](https://github.com/pingyhq/pingy-cli/wiki/Creating-a-Web-Scaffold) for [Pingy CLI](https://pin.gy/cli/) out of your Bulma templates, see here: https://github.com/pingyhq/pingy-scaffold-bulma

If you'd like to take ownership of the repo or anything like that then let me know.

You can close this issue :)

**Comment by dansup** [comment]
@davej Looks great, good work! I will add a "related projects" section to the readme and add this when I get a chance.
