### ISSUE TITLE
 Mobile friendly landing page

### ISSUE THREAD

**Issue by kunjee17** [dansup/bulma-templates#55]
Hi,

First of all thanks for your work with Bulma. Specially you are keeping the pace with latest updates. 

I was trying out landing page. It is saying that is mobile friendly but when I tried in mobile view, navigation seems to be broken. I can't see the menu. Am I missing something ?

And what is best JQuery free way to change active css for navigation. I was unable to figure that thing out. 

Again Thanks for your work.

**Comment by Talkingbaby** [comment]
Hey,

I just checked out the landing page. To make the hamburger menu functional
you can look here https://bulma.io/documentation/components/navbar/

The docs say that you need to either add the is active class to the menu
element or use javascript. The docs do give an example of how to add pure
javascript and not jquery.

**Comment by kunjee17** [comment]
@Talkingbaby hey thanks. I have tried but didn't worked out for me. I will have a look at it again... Thanks for reply.

**Comment by dansup** [comment]
@kunjee17 What @Talkingbaby said is correct, bulma is css only. You can use the vanilla javascript example on the bulma docs.
