### ISSUE TITLE
blog  : promo block content overflows box

### ISSUE THREAD

**Issue by diomed** [dansup/bulma-templates#61]
![overflows](https://user-images.githubusercontent.com/72777/36628982-2a2b9e7c-1950-11e8-856c-27746be871be.png)

**Comment by dansup** [comment]
@diomed You fixed this in b535c0d right?

**Comment by diomed** [comment]
sadly, no, I didn't.

I've looked at this yesterday: https://github.com/jgthms/bulma/pull/1641
maybe it'll help. I tried adding it as a property but with no success,
