### ISSUE TITLE
Any plan on adding a user profile page?

### ISSUE THREAD

**Issue by GabMic** [dansup/bulma-templates#82]
It would be a great addtion with plenty of "demand". 
This repo is great, thanks!

**Comment by diomed** [comment]
what do you think of this showcase: https://emkelley.github.io/EK-Bulma-Templates/

btw. I'm kinda hoping owner shall one day create official repo where other makers of bulma templates,
such as that one, shall share their templates under one official bulma templates organization

**Comment by GabMic** [comment]
@diomed Well, i think it is beautiful. Wish there was a profile template.

**Comment by GabMic** [comment]
Oh, you meant if a user profile would have that design? Yes, it will be great.

**Comment by mubaidr** [comment]
I would like to work on this issue to create a portfolio template. @dansup you can assign this to me.

**Comment by GabMic** [comment]
Are you starting this? @mubaidr

**Comment by mubaidr** [comment]
Yes, I am ready to work on this.

**Comment by GabMic** [comment]
Well, i guess that you forked it and submitted a pr?

**Comment by mubaidr** [comment]
No. I am asking if there is need to add portfolio template then I can work and create one. 
I have not yet completed this task.

**Comment by GabMic** [comment]
Oh, i see. I think there is a need, but also for a profile template especially. Thanks brother.

**Comment by mubaidr** [comment]
Progress: https://github.com/dansup/bulma-templates/pull/83

**Comment by mubaidr** [comment]
This should be closed. @dansup

**Comment by diomed** [comment]
@GabMic what is a profile layout, then? I did ask you to provide some kind of example, but you didn't.
