### ISSUE TITLE
release

### ISSUE THREAD

**Issue by diomed** [dansup/bulma-templates#86]
Now that everything is more or less tip-top,
it would be actually a very good move to create
a new release, since nothing was released for over a year now,
and everything is updated to 0.7.1.

perhaps it would be also good to version it as **0.7.1.** [per existing number version of bulma]

**Comment by dansup** [comment]
@diomed Yes, I agree. Before I do that I would like to go through each template and make sure everything works as expected. Will do that later today.

**Comment by diomed** [comment]
funnily enough, 0.7.2. was release just 2 days ago. 
maybe all templates should be updated to it.

**Comment by lowlevelm** [comment]
It looks like there where only additions, and no subtractions with the classes. i will be submitting a pull request later today

**Comment by diomed** [comment]
@dansup I think we no longer need Roadmap section, or at least not that line beneath it, since it refers to 0.6.0.

**Comment by dansup** [comment]
@diomed Done.
