### ISSUE TITLE
why was kanban excluded from index file?

### ISSUE THREAD

**Issue by diomed** [dansup/bulma-templates#88]
@lowlevelm 

looks like you commented it out.
by mistake or?

btw. it appears not to be responsive. maybe you could fix it?

**Comment by lowlevelm** [comment]
Hello @diomed, i believe it was that way when i cloned it, but i will look into it.

**Comment by lowlevelm** [comment]
I must have copy-pasted the code into a comment. i will fix that asap!

**Comment by diomed** [comment]
thanks. btw. if you know how, could you please make video responsive in tabs template.

**Comment by lowlevelm** [comment]
Fixed in #90
