### ISSUE TITLE
In electron-vue, display doesn't work

### ISSUE THREAD

**Issue by DarkScientist** [dansup/bulma-templates#95]
Hi,
I make a electron-vue app with templates and I've a problem ( I don't know if it is from bulma or vue / electron).

So, when I goes on the page where is the Kanban template, the scroll doesn't work and it displays a random part of the template, and it's locked, and I've to refresh to get a good display. I have no errors. 

The tabs and the Kanban templates make me this problem.

Thanks for helping

**Comment by dansup** [comment]
@DarkScientist Hi, that sounds like an issue with electron-vue.

**Comment by DarkScientist** [comment]
Hi,
I fixed that by resetting the head of the web page. 
I was using a lot of your templates and the modals locked the scroll. As electron vue doesn't refresh, it kept the scroll locked so by resetting the meta it worked. 
Thanks!
